import type {
  ActivityDraft,
  AdminMarket,
  AdminStatement,
  Asset,
  AuditEvent,
  Finding,
  ModerationCase,
  Person,
  QueueAlert,
  Release,
  SourceProject,
} from "./types";

export const people: Person[] = [
  {
    id: "lucy",
    name: "Lucy Chen",
    initials: "LC",
    roles: ["Editor", "Publisher", "Administrator"],
    email: "lucy@perdisco.app",
    status: "Active",
    lastActive: "Now",
  },
  {
    id: "priya",
    name: "Priya Raman",
    initials: "PR",
    roles: ["Producer", "Editor"],
    email: "priya@perdisco.app",
    status: "Active",
    lastActive: "12 min ago",
  },
  {
    id: "tom",
    name: "Tom Osei",
    initials: "TO",
    roles: ["Reviewer"],
    email: "tom@perdisco.app",
    status: "Active",
    lastActive: "1 hr ago",
  },
  {
    id: "sara",
    name: "Sara Kim",
    initials: "SK",
    roles: ["Reviewer", "Publisher"],
    email: "sara@perdisco.app",
    status: "Active",
    lastActive: "Yesterday",
  },
  {
    id: "diego",
    name: "Diego Alvarez",
    initials: "DA",
    roles: ["Moderator", "Market resolver"],
    email: "diego@perdisco.app",
    status: "Active",
    lastActive: "3 hr ago",
  },
  {
    id: "noor",
    name: "Noor Haddad",
    initials: "NH",
    roles: ["Producer"],
    email: "noor@perdisco.app",
    status: "Invited",
    lastActive: "—",
  },
];

const clearedRights = (owner: string, expiry: string): SourceProject["rights"] => ({
  owner,
  basis: "Written permission — summary, timestamped playback, attribution required",
  approvedUses: ["Ingest", "Transcribe", "Summarize", "Display", "Timestamp deep link"],
  restrictions: "No clipping over 90s · No model training · Attribution on every surface",
  mediaBehavior: "Embedded player with timestamp seek",
  expiry,
  takedownContact: "rights@perdisco.app",
  status: "Cleared",
  reviewer: "Sara Kim",
});

export const projects: SourceProject[] = [
  {
    id: "robot-economy",
    title: "What actually makes a robotics company investable?",
    shortTitle: "The Robot Economy",
    format: "Podcast",
    medium: "audio",
    creator: "Dr. Maya Chen",
    creatorRole: "Investor and robotics operator",
    publisher: "Machines at Work",
    canonicalUrl: "https://example.com/robot-economy",
    published: "July 28, 2026",
    duration: "2H 14M",
    category: "ROBOTICS",
    initials: "MC",
    gradient: ["#C8D98C", "#315A47"],
    language: "English",
    state: "In review",
    owner: "Lucy Chen",
    contributors: ["Priya Raman", "Tom Osei"],
    workspace: "Editorial",
    organization: "Perdisco",
    priority: "High",
    targetRelease: "Aug 4, 2026",
    updatedAt: "18 min ago",
    orientation:
      "A veteran robotics investor explains why demos mislead, why reliability compounds, and how outcome pricing reshapes the market.",
    blocks: [
      {
        kind: "text",
        id: "re-b1",
        text: "Robotics has spent years producing captivating demonstrations. The harder question is whether those machines can become reliable businesses.",
      },
      { kind: "statement", id: "re-b2", statementId: "s1" },
      {
        kind: "text",
        id: "re-b3",
        text: "The source starts by reframing the headline claim around the work a buyer actually needs completed.",
      },
      { kind: "statement", id: "re-b4", statementId: "s2" },
      { kind: "activity", id: "re-b5", activityId: "act2" },
      {
        kind: "text",
        id: "re-b6",
        text: "That changes the unit of analysis: reliability belongs to the complete workflow, not a single impressive action.",
      },
      { kind: "statement", id: "re-b7", statementId: "s3" },
      {
        kind: "text",
        id: "re-b8",
        text: "The argument then moves from technical capability to the business model that carries deployment risk.",
      },
      { kind: "statement", id: "re-b9", statementId: "s4" },
      { kind: "activity", id: "re-b10", activityId: "act4" },
      {
        kind: "text",
        id: "re-b11",
        text: "Taken together, the interview offers a practical lens: start with completed work, then reason backward to the technology required to deliver it.",
      },
    ],
    rights: clearedRights("Machines at Work Media LLC", "July 2027"),
    processing: [
      { name: "Media inspection", status: "Complete", detail: "RSS enclosure validated · 2h 14m · 128kbps" },
      { name: "Transcription", status: "Complete", detail: "Publisher transcript, time-aligned, 2 speakers" },
      { name: "Podcast synchronization", status: "Complete", detail: "RSS primary · YouTube fallback aligned, drift 0.4s" },
      { name: "Normalization", status: "Complete", detail: "412 segments · anchors stable" },
      { name: "AI assistance", status: "Complete", detail: "6 statement suggestions · run em-2026-07-29-114" },
      { name: "Preflight", status: "Needs review", detail: "1 low-confidence transcript region used by s3" },
    ],
    gates: [
      { name: "Editorial fidelity", status: "Approved", reviewer: "Tom Osei" },
      { name: "Evidence & research", status: "In review", reviewer: "Tom Osei" },
      { name: "Rights & source use", status: "Approved", reviewer: "Sara Kim" },
      { name: "Learning quality", status: "Changes requested", reviewer: "Sara Kim", note: "Quiz distractor overlaps answer" },
      { name: "Community", status: "Approved", reviewer: "Diego Alvarez" },
      { name: "Market", status: "In review", reviewer: "Diego Alvarez" },
      { name: "Accessibility & technical", status: "Not started" },
    ],
    blockers: [],
    version: 3,
    playback: {
      primary: "RSS · Machines at Work feed · episode 214",
      fallback: "YouTube · machinesatwork/ep214",
      transcriptSource: "Publisher-supplied, time-aligned",
      transcriptState: "Aligned",
    },
  },
  {
    id: "reliability-paper",
    title: "Reliability thresholds for autonomous systems in real workflows",
    shortTitle: "Reliability Thresholds",
    format: "Research paper",
    medium: "pdf",
    creator: "Stanford HAI Systems Lab",
    creatorRole: "Peer-reviewed systems research",
    publisher: "Journal of Autonomous Systems",
    canonicalUrl: "https://example.com/reliability-thresholds",
    published: "July 24, 2026",
    duration: "22 MIN READ",
    category: "AI SYSTEMS",
    initials: "HAI",
    gradient: ["#CBDCF2", "#476982"],
    language: "English",
    state: "Published",
    owner: "Priya Raman",
    contributors: ["Lucy Chen"],
    workspace: "Editorial",
    organization: "Perdisco",
    priority: "Normal",
    targetRelease: "Live since Jul 26",
    updatedAt: "2 days ago",
    orientation:
      "A peer-reviewed study of 43 deployments showing why intervention frequency, not benchmark accuracy, predicts operating cost.",
    blocks: [
      {
        kind: "text",
        id: "rp-b1",
        text: "Headline task-completion rates hide the real operating cost of autonomous systems. Field reliability depends on how errors compound and how well a system recovers.",
      },
      { kind: "statement", id: "rp-b2", statementId: "s5" },
      {
        kind: "text",
        id: "rp-b3",
        text: "From that finding the authors ask what a benchmark should reward instead.",
      },
      { kind: "statement", id: "rp-b4", statementId: "s6" },
      {
        kind: "text",
        id: "rp-b5",
        text: "The paper argues for evaluation that follows an entire job through failure, escalation, recovery, and completion.",
      },
    ],
    rights: {
      owner: "Journal of Autonomous Systems",
      basis: "Open-access license (CC BY 4.0)",
      approvedUses: ["Ingest", "Extract", "Summarize", "Display", "Cite"],
      restrictions: "Attribution required · No figure reproduction without credit",
      mediaBehavior: "External link to paper of record",
      expiry: "None",
      takedownContact: "rights@perdisco.app",
      status: "Cleared",
      reviewer: "Sara Kim",
    },
    processing: [
      { name: "Media inspection", status: "Complete", detail: "PDF, 31 pages, born-digital" },
      { name: "Document extraction", status: "Complete", detail: "Sections, figures, citations extracted" },
      { name: "Normalization", status: "Complete", detail: "Page + section anchors stable" },
      { name: "AI assistance", status: "Complete", detail: "3 suggestions · run em-2026-07-24-031" },
      { name: "Preflight", status: "Complete", detail: "All checks pass" },
    ],
    gates: [
      { name: "Editorial fidelity", status: "Approved", reviewer: "Tom Osei" },
      { name: "Evidence & research", status: "Approved", reviewer: "Tom Osei" },
      { name: "Rights & source use", status: "Approved", reviewer: "Sara Kim" },
      { name: "Learning quality", status: "Approved", reviewer: "Sara Kim" },
      { name: "Community", status: "Approved", reviewer: "Diego Alvarez" },
      { name: "Market", status: "Approved", reviewer: "Diego Alvarez" },
      { name: "Accessibility & technical", status: "Approved", reviewer: "Sara Kim" },
    ],
    blockers: [],
    version: 2,
    playback: {
      primary: "Document · paper of record",
      transcriptSource: "Not applicable",
      transcriptState: "Aligned",
    },
  },
  {
    id: "biology-engineering",
    title: "Biology is becoming an engineering discipline",
    shortTitle: "Biology as Engineering",
    format: "Interview",
    medium: "video",
    creator: "Nina Okafor",
    creatorRole: "Synthetic biology founder",
    publisher: "Perdisco Interviews",
    canonicalUrl: "https://example.com/biology-engineering",
    published: "July 21, 2026",
    duration: "1H 36M",
    category: "BIOTECH",
    initials: "NO",
    gradient: ["#D6C8EA", "#5A4776"],
    language: "English",
    state: "Processing",
    owner: "Priya Raman",
    contributors: ["Noor Haddad"],
    workspace: "Editorial",
    organization: "Perdisco",
    priority: "Normal",
    targetRelease: "Aug 12, 2026",
    updatedAt: "41 min ago",
    orientation:
      "A founder interview on why wet-lab turnaround time is the clock speed of biotech, and what biofoundries change.",
    blocks: [
      {
        kind: "text",
        id: "be-b1",
        text: "Biology is moving from discovery toward design, but progress is still governed by the speed and reliability of physical experimentation.",
      },
      { kind: "statement", id: "be-b2", statementId: "s7" },
      { kind: "statement", id: "be-b3", statementId: "s8" },
      {
        kind: "text",
        id: "be-b4",
        text: "The most valuable tools may be the ones that compress the loop between a biological hypothesis and a trustworthy result.",
      },
    ],
    rights: clearedRights("Perdisco Studios (first party)", "None"),
    processing: [
      { name: "Media inspection", status: "Complete", detail: "Video master 1080p validated" },
      { name: "Transcription", status: "Running", detail: "Speaker alignment 74% complete" },
      { name: "Caption generation", status: "Waiting", detail: "Blocked on transcript completion" },
      { name: "AI assistance", status: "Waiting", detail: "Queued after normalization" },
      { name: "Preflight", status: "Waiting", detail: "—" },
    ],
    gates: [
      { name: "Editorial fidelity", status: "Not started" },
      { name: "Evidence & research", status: "Not started" },
      { name: "Rights & source use", status: "Approved", reviewer: "Sara Kim" },
      { name: "Learning quality", status: "Not started" },
      { name: "Community", status: "Not started" },
      { name: "Market", status: "Not started" },
      { name: "Accessibility & technical", status: "Not started" },
    ],
    blockers: [],
    version: 1,
    playback: {
      primary: "Hosted video · Perdisco media store",
      transcriptSource: "Machine-generated, in progress",
      transcriptState: "Low confidence",
    },
  },
  {
    id: "scaling",
    title: "The case against scaling at all costs",
    shortTitle: "Against Scaling at All Costs",
    format: "Article",
    medium: "text",
    creator: "Jon Bell",
    creatorRole: "Founder and early-stage investor",
    publisher: "Field Notes",
    canonicalUrl: "https://example.com/scaling",
    published: "July 18, 2026",
    duration: "14 MIN READ",
    category: "STARTUPS",
    initials: "JB",
    gradient: ["#F0D3BC", "#8C5E3F"],
    language: "English",
    state: "Scheduled",
    owner: "Lucy Chen",
    contributors: ["Tom Osei"],
    workspace: "Editorial",
    organization: "Perdisco",
    priority: "Normal",
    targetRelease: "Aug 1, 2026 · 09:00",
    updatedAt: "5 hr ago",
    orientation:
      "An argument that scaling before retention becomes operational knowledge is expensive theater — with a lens for spotting hidden markets.",
    blocks: [
      {
        kind: "text",
        id: "sc-b1",
        text: "Growth can hide whether a company has learned how value is actually created. Operational knowledge should precede aggressive expansion.",
      },
      { kind: "statement", id: "sc-b2", statementId: "s9" },
      {
        kind: "text",
        id: "sc-b3",
        text: "If growth is not the first milestone, the article suggests what to look for instead.",
      },
      { kind: "statement", id: "sc-b4", statementId: "s10" },
      { kind: "activity", id: "sc-b5", activityId: "act5" },
      {
        kind: "text",
        id: "sc-b6",
        text: "Scale is an amplifier. It strengthens a working system and makes a confused one more expensive.",
      },
    ],
    rights: {
      owner: "Field Notes / Jon Bell",
      basis: "Platform syndication terms — summary + link-out",
      approvedUses: ["Ingest", "Summarize", "Display", "Link out"],
      restrictions: "No full-text reproduction · Canonical link required",
      mediaBehavior: "External link",
      expiry: "January 2027",
      takedownContact: "rights@perdisco.app",
      status: "Cleared",
      reviewer: "Sara Kim",
    },
    processing: [
      { name: "Media inspection", status: "Complete", detail: "Canonical URL resolved" },
      { name: "Document extraction", status: "Complete", detail: "Headings + sections extracted" },
      { name: "Normalization", status: "Complete", detail: "Anchors stable" },
      { name: "AI assistance", status: "Complete", detail: "4 suggestions · run em-2026-07-19-208" },
      { name: "Preflight", status: "Complete", detail: "All checks pass" },
    ],
    gates: [
      { name: "Editorial fidelity", status: "Approved", reviewer: "Tom Osei" },
      { name: "Evidence & research", status: "Approved", reviewer: "Tom Osei" },
      { name: "Rights & source use", status: "Approved", reviewer: "Sara Kim" },
      { name: "Learning quality", status: "Approved", reviewer: "Sara Kim" },
      { name: "Community", status: "Approved", reviewer: "Diego Alvarez" },
      { name: "Market", status: "Approved", reviewer: "Diego Alvarez" },
      { name: "Accessibility & technical", status: "Approved", reviewer: "Sara Kim" },
    ],
    blockers: [],
    version: 1,
    playback: {
      primary: "Text · in-app summary with canonical link",
      transcriptSource: "Not applicable",
      transcriptState: "Aligned",
    },
  },
  {
    id: "grid-storage",
    title: "Why grid-scale storage deals keep falling apart",
    shortTitle: "Grid Storage Deals",
    format: "Podcast",
    medium: "audio",
    creator: "Amara Diallo",
    creatorRole: "Energy analyst",
    publisher: "The Load Curve",
    canonicalUrl: "https://example.com/grid-storage",
    published: "July 27, 2026",
    duration: "1H 02M",
    category: "ENERGY",
    initials: "AD",
    gradient: ["#CBDCF2", "#2F5D77"],
    language: "English",
    state: "Blocked",
    owner: "Noor Haddad",
    contributors: ["Priya Raman"],
    workspace: "Editorial",
    organization: "Perdisco",
    priority: "High",
    targetRelease: "Aug 8, 2026",
    updatedAt: "1 hr ago",
    orientation: "",
    blocks: [],
    rights: {
      owner: "The Load Curve",
      basis: "Podcast platform terms — under review",
      approvedUses: ["Ingest", "Transcribe"],
      restrictions: "Playback rights unconfirmed",
      mediaBehavior: "Undetermined",
      expiry: "—",
      takedownContact: "rights@perdisco.app",
      status: "Pending review",
      reviewer: "—",
    },
    processing: [
      { name: "Media inspection", status: "Complete", detail: "RSS enclosure validated · 1h 02m" },
      { name: "Transcription", status: "Failed", detail: "No transcript in feed; generation needs rights sign-off" },
      { name: "Podcast synchronization", status: "Waiting", detail: "Blocked on transcript" },
      { name: "Preflight", status: "Waiting", detail: "—" },
    ],
    gates: [
      { name: "Editorial fidelity", status: "Not started" },
      { name: "Evidence & research", status: "Not started" },
      { name: "Rights & source use", status: "Blocked", note: "Playback basis unconfirmed" },
      { name: "Learning quality", status: "Not started" },
      { name: "Community", status: "Not started" },
      { name: "Market", status: "Not started" },
      { name: "Accessibility & technical", status: "Not started" },
    ],
    blockers: [
      {
        object: "Transcript",
        reason: "Podcast intake requires a time-aligned transcript before composition",
        responsibleRole: "Producer",
        resolution: "Import publisher transcript or clear rights for machine transcription",
        overridable: false,
      },
      {
        object: "Rights record",
        reason: "Playback basis unconfirmed — embedded player cannot be approved",
        responsibleRole: "Publisher",
        resolution: "Confirm platform terms or obtain written permission",
        overridable: true,
      },
    ],
    version: 1,
    playback: {
      primary: "RSS · The Load Curve · episode 88",
      transcriptSource: "Missing",
      transcriptState: "Missing",
    },
  },
  {
    id: "attention-markets",
    title: "The attention recession: why engagement metrics mislead",
    shortTitle: "The Attention Recession",
    format: "Article",
    medium: "text",
    creator: "Wei Zhang",
    creatorRole: "Media economist",
    publisher: "Signal & Noise",
    canonicalUrl: "https://example.com/attention-recession",
    published: "July 12, 2026",
    duration: "11 MIN READ",
    category: "MEDIA",
    initials: "WZ",
    gradient: ["#E8DDF3", "#5A4776"],
    language: "English",
    state: "Changes requested",
    owner: "Priya Raman",
    contributors: ["Tom Osei"],
    workspace: "Editorial",
    organization: "Perdisco",
    priority: "Low",
    targetRelease: "Aug 15, 2026",
    updatedAt: "Yesterday",
    blocks: [
      {
        kind: "text",
        id: "am-b1",
        text: "Engagement totals keep rising while the attention behind them thins out. The article separates measured activity from felt attention.",
      },
      {
        kind: "text",
        id: "am-b2",
        text: "Metrics that price attention by the second will misprice everything that takes a minute to matter.",
      },
    ],
    orientation:
      "Why headline engagement growth can coincide with declining real attention — and what that does to ad-financed media.",
    rights: clearedRights("Signal & Noise", "March 2027"),
    processing: [
      { name: "Media inspection", status: "Complete", detail: "Canonical URL resolved" },
      { name: "Document extraction", status: "Complete", detail: "Sections extracted" },
      { name: "AI assistance", status: "Complete", detail: "5 suggestions · run em-2026-07-13-142" },
      { name: "Preflight", status: "Complete", detail: "All checks pass" },
    ],
    gates: [
      { name: "Editorial fidelity", status: "Changes requested", reviewer: "Tom Osei", note: "Two statements read as opinion but are classified FACT" },
      { name: "Evidence & research", status: "In review", reviewer: "Tom Osei" },
      { name: "Rights & source use", status: "Approved", reviewer: "Sara Kim" },
      { name: "Learning quality", status: "Not started" },
      { name: "Community", status: "Not started" },
      { name: "Market", status: "Not started" },
      { name: "Accessibility & technical", status: "Not started" },
    ],
    blockers: [],
    version: 1,
    playback: {
      primary: "Text · in-app summary with canonical link",
      transcriptSource: "Not applicable",
      transcriptState: "Aligned",
    },
  },
];

export const statements: AdminStatement[] = [
  {
    id: "s1",
    projectId: "robot-economy",
    type: "FORECAST",
    text: "The cost of useful robot labor will fall below $10 an hour before 2030.",
    context:
      "Maya’s view is that hardware cost is no longer the only constraint. Better foundation models, richer training data, and remote human intervention can push utilization high enough to make robots economical in structured industrial settings first.",
    locator: "42:16",
    sourceMoment:
      "The key is useful labor—not the sticker price of a robot, but the cost of each completed hour of work.",
    supportingSource: "International Federation of Robotics cost benchmark",
    supportingUrl: "https://ifr.org/",
    topic: "ROBOTICS",
    learningEligible: true,
    attribution: "Dr. Maya Chen",
    anchor: "robot-economy/v3#s1",
    aiSuggested: true,
    aiModelRun: "em-2026-07-29-114",
    elaborationState: "Complete",
    discussionEnabled: true,
  },
  {
    id: "s2",
    projectId: "robot-economy",
    type: "FACT",
    text: "A robot that works 90% of the time is often less useful than it sounds.",
    context:
      "In a 100-step workflow, a 90% success rate per step compounds into near-certain failure. Buyers care about completed jobs, not impressive individual actions. Reliability, recovery, and escalation are part of the product.",
    locator: "58:03",
    sourceMoment:
      "The important number isn’t success per action. It is completed jobs without a person stepping in.",
    supportingSource: "Reliability thresholds for autonomous systems",
    supportingUrl: "https://example.com/reliability-thresholds",
    topic: "ROBOTICS",
    learningEligible: true,
    attribution: "Dr. Maya Chen",
    anchor: "robot-economy/v3#s2",
    aiSuggested: false,
    elaborationState: "Complete",
    discussionEnabled: true,
  },
  {
    id: "s3",
    projectId: "robot-economy",
    type: "MENTAL MODEL",
    text: "Look for the boring workflow hiding behind the flashy demo.",
    context:
      "The most investable robotics companies often begin with repetitive, measurable workflows. A compelling demo earns attention; a workflow with a clear owner, budget, and definition of done creates a durable business.",
    locator: "1:21:44",
    sourceMoment:
      "Find the person who owns the failure today. That is usually where the real market starts.",
    supportingSource: "Field deployment operating checklist",
    supportingUrl: "https://example.com/deployment-checklist",
    topic: "ROBOTICS",
    learningEligible: true,
    attribution: "Dr. Maya Chen",
    anchor: "robot-economy/v3#s3",
    aiSuggested: true,
    aiModelRun: "em-2026-07-29-114",
    elaborationState: "Draft",
    discussionEnabled: true,
  },
  {
    id: "s4",
    projectId: "robot-economy",
    type: "OPINION",
    text: "The winning robotics companies will sell outcomes, not machines.",
    context:
      "Customers want pallets moved, rooms cleaned, or inspections completed. Outcome pricing shifts deployment and reliability risk toward the vendor, while making the value proposition easier to understand.",
    locator: "1:46:11",
    sourceMoment:
      "The customer should be buying the finished job. The machine is how you deliver it.",
    supportingSource: "Robotics-as-a-service adoption study",
    supportingUrl: "https://example.com/raas",
    topic: "ROBOTICS",
    learningEligible: true,
    attribution: "Dr. Maya Chen",
    anchor: "robot-economy/v3#s4",
    aiSuggested: false,
    elaborationState: "Complete",
    discussionEnabled: true,
  },
  {
    id: "s5",
    projectId: "reliability-paper",
    type: "FACT",
    text: "Per-step reliability can wildly overstate completed-job reliability.",
    context:
      "A workflow made of many dependent steps compounds individual error rates. Evaluation must measure whether the whole job finishes within acceptable intervention and recovery limits.",
    locator: "p. 14 · Figure 3",
    sourceMoment:
      "Across 43 deployments, intervention frequency predicted operating cost more reliably than isolated benchmark accuracy.",
    supportingSource: "Journal replication dataset",
    supportingUrl: "https://example.com/dataset",
    topic: "AI SYSTEMS",
    learningEligible: true,
    attribution: "Stanford HAI Systems Lab",
    anchor: "reliability-paper/v2#s5",
    aiSuggested: false,
    elaborationState: "Complete",
    discussionEnabled: true,
  },
  {
    id: "s6",
    projectId: "reliability-paper",
    type: "OPINION",
    text: "Benchmarks should measure recovery from failure, not only task completion.",
    context:
      "A system that notices uncertainty, asks for help, and resumes safely may be more valuable than one with a higher headline completion score but brittle failure behavior.",
    locator: "p. 27 · Discussion",
    sourceMoment:
      "Recovery time and escalation quality should be first-class benchmark outputs.",
    supportingSource: "NIST AI Risk Management Framework",
    supportingUrl: "https://www.nist.gov/itl/ai-risk-management-framework",
    topic: "AI SYSTEMS",
    learningEligible: true,
    attribution: "Study authors",
    anchor: "reliability-paper/v2#s6",
    aiSuggested: false,
    elaborationState: "Complete",
    discussionEnabled: true,
  },
  {
    id: "s7",
    projectId: "biology-engineering",
    type: "FORECAST",
    text: "The best biofoundries will shrink a month-long learning loop to under 48 hours.",
    context:
      "Automation matters because it compresses design, build, test, and learn cycles. Faster cycles generate better proprietary datasets and improve the next experiment.",
    locator: "31:08",
    sourceMoment:
      "The real advantage is not one great experiment. It is how quickly the system learns from the last one.",
    supportingSource: "Global Biofoundry Alliance",
    supportingUrl: "https://globalbiofoundriesalliance.org/",
    topic: "BIOTECH",
    learningEligible: true,
    attribution: "Nina Okafor",
    anchor: "biology-engineering/v1#s7",
    aiSuggested: true,
    aiModelRun: "em-2026-07-22-067",
    elaborationState: "Draft",
    discussionEnabled: true,
  },
  {
    id: "s8",
    projectId: "biology-engineering",
    type: "MENTAL MODEL",
    text: "Treat wet-lab turnaround time as biology’s clock speed.",
    context:
      "Software iteration is cheap and fast; biological iteration is constrained by physical growth, measurement, and validation. Teams that compress reliable turnaround can compound learning faster.",
    locator: "52:41",
    sourceMoment:
      "Every day removed from the loop is another chance to learn before a competitor.",
    supportingSource: "Biofoundry cycle-time review",
    supportingUrl: "https://example.com/biofoundry",
    topic: "BIOTECH",
    learningEligible: true,
    attribution: "Nina Okafor",
    anchor: "biology-engineering/v1#s8",
    aiSuggested: false,
    elaborationState: "Empty",
    discussionEnabled: false,
  },
  {
    id: "s9",
    projectId: "scaling",
    type: "OPINION",
    text: "Scaling before retention becomes operational knowledge is expensive theater.",
    context:
      "Growth can temporarily hide weak activation, unclear value, and manual work. The article argues that expansion should follow an explicit model of why customers stay.",
    locator: "6 min read",
    sourceMoment:
      "Growth is not a substitute for knowing which behavior creates durable value.",
    supportingSource: "SaaS retention benchmark",
    supportingUrl: "https://example.com/retention",
    topic: "STARTUPS",
    learningEligible: true,
    attribution: "Jon Bell",
    anchor: "scaling/v1#s9",
    aiSuggested: false,
    elaborationState: "Complete",
    discussionEnabled: true,
  },
  {
    id: "s10",
    projectId: "scaling",
    type: "MENTAL MODEL",
    text: "A market that looks small may be a workflow that has never had a budget owner.",
    context:
      "Some emerging markets are hidden inside fragmented operating expenses. Before estimating demand, identify who feels the pain, who can approve a purchase, and which line item the product replaces.",
    locator: "10 min read",
    sourceMoment:
      "A missing category is often a missing owner, not missing demand.",
    supportingSource: "Enterprise buying-center research",
    supportingUrl: "https://example.com/buying-centers",
    topic: "STARTUPS",
    learningEligible: true,
    attribution: "Jon Bell",
    anchor: "scaling/v1#s10",
    aiSuggested: true,
    aiModelRun: "em-2026-07-19-208",
    elaborationState: "Complete",
    discussionEnabled: true,
  },
];

export const aiSuggestions = [
  {
    id: "sg1",
    projectId: "robot-economy",
    type: "FACT" as const,
    text: "Warehouse robotics deployments doubled between 2023 and 2026.",
    locator: "1:12:30",
    modelRun: "em-2026-07-29-114",
    confidence: "High",
    note: "Speaker cites IFR data; verify against the 2026 benchmark before accepting.",
  },
  {
    id: "sg2",
    projectId: "robot-economy",
    type: "OPINION" as const,
    text: "Hardware margins will stay thin until robots own their service contracts.",
    locator: "1:58:45",
    modelRun: "em-2026-07-29-114",
    confidence: "Medium",
    note: "Paraphrase spans two answers; check attribution boundary.",
  },
];

export const findings: Finding[] = [
  {
    id: "f1",
    projectId: "robot-economy",
    gate: "Learning quality",
    target: "Applied quiz · s2",
    severity: "Major",
    note: "Distractor B is defensibly correct for the surgery ranking; tighten the rubric or replace the option.",
    author: "Sara Kim",
    state: "Open",
    createdAt: "Today · 09:41",
  },
  {
    id: "f2",
    projectId: "robot-economy",
    gate: "Evidence & research",
    target: "Statement s3 · supporting source",
    severity: "Minor",
    note: "Deployment checklist link is a secondary blog mirror — cite the original operator document.",
    author: "Tom Osei",
    state: "Open",
    createdAt: "Today · 08:15",
  },
  {
    id: "f3",
    projectId: "robot-economy",
    gate: "Market",
    target: "Market · warehouse-outcomes",
    severity: "Blocker",
    note: "Resolution source names 'top five vendors' without listing them. Fix the authoritative list before open.",
    author: "Diego Alvarez",
    state: "Open",
    createdAt: "Yesterday · 17:02",
  },
  {
    id: "f4",
    projectId: "attention-markets",
    gate: "Editorial fidelity",
    target: "Statements 2 and 4",
    severity: "Major",
    note: "Both read as the author's judgment but are classified FACT. Reclassify as OPINION or add verification basis.",
    author: "Tom Osei",
    state: "Open",
    createdAt: "Yesterday · 11:20",
  },
  {
    id: "f5",
    projectId: "reliability-paper",
    gate: "Accessibility & technical",
    target: "Figure 3 alt text",
    severity: "Minor",
    note: "Alt text describes the chart type, not the finding. Rewrote during review — verify.",
    author: "Sara Kim",
    state: "Resolved",
    createdAt: "Jul 25 · 15:44",
  },
];

export const releases: Release[] = [
  {
    id: "r1",
    projectId: "scaling",
    version: 1,
    state: "Scheduled",
    when: "Aug 1, 2026 · 09:00",
    publisher: "Lucy Chen",
    cohort: "All users",
    health: "—",
  },
  {
    id: "r2",
    projectId: "reliability-paper",
    version: 2,
    state: "Live",
    when: "Jul 26, 2026 · 09:00",
    publisher: "Sara Kim",
    cohort: "All users",
    health: "Healthy",
    note: "v2 correction: Figure 3 alt text + dataset citation",
  },
  {
    id: "r3",
    projectId: "reliability-paper",
    version: 1,
    state: "Corrected",
    when: "Jul 24, 2026 · 09:00",
    publisher: "Sara Kim",
    cohort: "All users",
    health: "—",
    note: "Superseded by v2",
  },
  {
    id: "r4",
    projectId: "robot-economy",
    version: 2,
    state: "Failed",
    when: "Jul 29, 2026 · 17:30",
    publisher: "Lucy Chen",
    cohort: "Internal cohort",
    health: "Failing",
    note: "Client payload rejected: anchor map missing s3. Retry after preflight fix.",
  },
];

export const moderationCases: ModerationCase[] = [
  {
    id: "m1",
    kind: "Comment report",
    severity: "High",
    status: "New",
    projectId: "reliability-paper",
    statementId: "s5",
    reportedUser: "gridlock_88",
    excerpt: "This lab is paid to say this. Everyone involved should be [removed]…",
    reports: 6,
    aiSignal: "Harassment 0.92 · Coordinated pattern with 2 sibling accounts",
    slaHours: 4,
    assignee: "Diego Alvarez",
  },
  {
    id: "m2",
    kind: "Comment report",
    severity: "Medium",
    status: "In review",
    projectId: "robot-economy",
    reportedUser: "botfarm_capital",
    excerpt: "DM me for the real robotics picks before this market closes 🚀🚀",
    reports: 3,
    aiSignal: "Spam 0.88 · Market-adjacent solicitation",
    slaHours: 12,
    assignee: "Diego Alvarez",
  },
  {
    id: "m3",
    kind: "Appeal",
    severity: "Medium",
    status: "New",
    projectId: "scaling",
    reportedUser: "operator_jane",
    excerpt: "My comment cited my own company's numbers — that isn't self-promotion, it's evidence.",
    reports: 1,
    aiSignal: "Appeal of hide action · prior removal by rule 4.2",
    slaHours: 24,
  },
  {
    id: "m4",
    kind: "Thread report",
    severity: "Low",
    status: "Closed",
    projectId: "biology-engineering",
    reportedUser: "—",
    excerpt: "Thread drifted into unrelated supplement claims.",
    reports: 2,
    aiSignal: "Off-topic drift 0.71",
    slaHours: 48,
    assignee: "Diego Alvarez",
  },
];

export const markets: AdminMarket[] = [
  {
    id: "warehouse-outcomes",
    projectId: "robot-economy",
    statementId: "s4",
    question:
      "By 2029, will more than 25% of newly built large warehouses use outcome-priced robotics?",
    state: "In review",
    closes: "Dec 15, 2028",
    resolves: "Jan 31, 2029",
    communityProbability: 57,
    committedTokens: 0,
    participants: 0,
    concentration: "—",
    minStake: 10,
    maxStake: 500,
    resolutionSource: "Top five warehouse automation vendors’ public deployment data",
    rule: "Resolves YES if at least 25% of qualifying new warehouses report outcome-priced robotics contracts.",
    resolver: "Diego Alvarez",
    flag: "Blocker finding open: authoritative vendor list undefined",
  },
  {
    id: "robot-labor",
    projectId: "robot-economy",
    statementId: "s1",
    question: "Will useful robot labor cost less than $10 per hour by 2030?",
    state: "Open",
    closes: "Dec 15, 2029",
    resolves: "Jan 31, 2030",
    communityProbability: 68,
    committedTokens: 41250,
    participants: 312,
    concentration: "Top 10 hold 22%",
    minStake: 10,
    maxStake: 500,
    resolutionSource: "Independent warehouse labor-cost benchmark",
    rule: "Resolves YES if the benchmark reports an all-in median below $10 per completed operating hour.",
    resolver: "Diego Alvarez",
  },
  {
    id: "biofoundry-loop",
    projectId: "biology-engineering",
    statementId: "s7",
    question: "Will a major biofoundry publish a validated sub-48-hour design-build-test cycle by mid-2028?",
    state: "Draft",
    closes: "Jun 1, 2028",
    resolves: "Jul 15, 2028",
    communityProbability: 0,
    committedTokens: 0,
    participants: 0,
    concentration: "—",
    minStake: 10,
    maxStake: 250,
    resolutionSource: "Peer-reviewed publication or audited facility report",
    rule: "Resolves YES on a validated, reproducible cycle under 48 hours for a standard organism class.",
    resolver: "—",
  },
  {
    id: "attention-pricing",
    projectId: "attention-markets",
    statementId: "—",
    question: "Will a top-10 ad platform ship attention-quality pricing by end of 2027?",
    state: "Awaiting resolution",
    closes: "Closed Jul 15, 2026",
    resolves: "Due Aug 2, 2026",
    communityProbability: 44,
    committedTokens: 18730,
    participants: 149,
    concentration: "Top 10 hold 31%",
    minStake: 10,
    maxStake: 500,
    resolutionSource: "Platform product documentation and earnings disclosures",
    rule: "Resolves YES if pricing weights verified attention duration or quality, not raw impressions.",
    resolver: "Diego Alvarez",
    flag: "Resolution due in 2 days",
  },
];

export const assets: Asset[] = [
  {
    id: "a1",
    projectId: "robot-economy",
    kind: "Audio",
    name: "ep214-master.mp3",
    status: "Ready",
    meta: "2h 14m · 128kbps · RSS enclosure",
    updatedAt: "Jul 29",
  },
  {
    id: "a2",
    projectId: "robot-economy",
    kind: "Transcript",
    name: "ep214-transcript-aligned.json",
    status: "Needs review",
    meta: "412 segments · 1 low-confidence region (1:21:02–1:22:10)",
    updatedAt: "Jul 29",
  },
  {
    id: "a3",
    projectId: "robot-economy",
    kind: "Rights evidence",
    name: "machines-at-work-permission.pdf",
    status: "Ready",
    meta: "Signed Jul 14, 2026 · expires Jul 2027",
    updatedAt: "Jul 14",
  },
  {
    id: "a4",
    projectId: "biology-engineering",
    kind: "Video",
    name: "okafor-interview-1080p.mp4",
    status: "Ready",
    meta: "1h 36m · 1080p master",
    updatedAt: "Jul 21",
  },
  {
    id: "a5",
    projectId: "biology-engineering",
    kind: "Transcript",
    name: "okafor-transcript-draft.json",
    status: "Processing",
    meta: "Speaker alignment 74%",
    updatedAt: "41 min ago",
  },
  {
    id: "a6",
    projectId: "reliability-paper",
    kind: "Document",
    name: "reliability-thresholds-v2.pdf",
    status: "Ready",
    meta: "31 pages · born-digital · sections extracted",
    updatedAt: "Jul 24",
  },
  {
    id: "a7",
    projectId: "grid-storage",
    kind: "Audio",
    name: "load-curve-ep88.mp3",
    status: "Ready",
    meta: "1h 02m · RSS enclosure",
    updatedAt: "Jul 27",
  },
  {
    id: "a8",
    projectId: "grid-storage",
    kind: "Transcript",
    name: "—",
    status: "Failed",
    meta: "No transcript in feed · generation blocked on rights",
    updatedAt: "1 hr ago",
  },
  {
    id: "a9",
    projectId: "scaling",
    kind: "Image",
    name: "field-notes-cover.png",
    status: "Ready",
    meta: "1600×900 · hero variant generated",
    updatedAt: "Jul 18",
  },
];

export const activityDrafts: ActivityDraft[] = [
  {
    id: "act1",
    projectId: "robot-economy",
    statementId: "s2",
    mode: "Flashcard",
    prompt: "Which metric better separates a compelling robot demo from a viable deployment?",
    status: "Approved",
    aiSuggested: false,
    answer: "Completed jobs before a person must intervene.",
    explanation:
      "A buyer pays for completed work. Individual actions only matter insofar as they combine into reliable jobs.",
    reward: 12,
  },
  {
    id: "act2",
    projectId: "robot-economy",
    statementId: "s2",
    mode: "Applied quiz",
    prompt: "Rank these industries from most to least suitable for a robot that succeeds 90% of the time.",
    status: "In review",
    aiSuggested: true,
    explanation:
      "Crop monitoring tolerates missed passes; inventory scans are reversible; delivery failures affect customers; surgery requires near-zero failure.",
    reward: 20,
    options: [
      "Crop monitoring → Inventory scanning → Hotel delivery → Surgery",
      "Surgery → Hotel delivery → Inventory scanning → Crop monitoring",
      "Inventory scanning → Surgery → Crop monitoring → Hotel delivery",
      "Hotel delivery → Crop monitoring → Surgery → Inventory scanning",
    ],
    correctIndex: 0,
  },
  {
    id: "act3",
    projectId: "robot-economy",
    statementId: "s2",
    mode: "Matching",
    prompt: "Match each environment to the constraint that matters most.",
    status: "Approved",
    aiSuggested: false,
    matchingRows: [
      { left: "Open-field crop monitoring", right: "Missed passes are tolerable" },
      { left: "Warehouse inventory scanning", right: "Structured and reversible" },
      { left: "Robot-assisted surgery", right: "Near-zero failure tolerance" },
    ],
    explanation:
      "Suitability depends on the consequence, reversibility, and recovery cost of an error—not the headline success rate alone.",
    reward: 20,
  },
  {
    id: "act4",
    projectId: "robot-economy",
    statementId: "s4",
    mode: "Prediction",
    prompt: "Will outcome-priced robotics reach more than 25% of new large warehouses by 2029?",
    status: "In review",
    aiSuggested: false,
    explanation:
      "Combine the source's pricing thesis with integration cycles, warehouse replacement rates, labor costs, and improving reliability.",
    marketId: "warehouse-outcomes",
  },
  {
    id: "act5",
    projectId: "scaling",
    statementId: "s9",
    mode: "Poll",
    prompt: "Has your team ever scaled a process you later had to unwind?",
    status: "Approved",
    aiSuggested: true,
    reward: 5,
    options: ["Yes", "Not yet"],
  },
];

export const auditEvents: AuditEvent[] = [
  {
    id: "e1",
    time: "Today · 10:52",
    actor: "Lucy Chen",
    role: "Editor",
    action: "Statement reordered",
    object: "robot-economy · v3 draft",
    detail: "s3 moved from position 4 to 3",
    protected: false,
  },
  {
    id: "e2",
    time: "Today · 09:41",
    actor: "Sara Kim",
    role: "Reviewer",
    action: "Changes requested",
    object: "robot-economy · Learning quality gate",
    detail: "Finding f1 attached to applied quiz",
    protected: false,
  },
  {
    id: "e3",
    time: "Yesterday · 17:30",
    actor: "Lucy Chen",
    role: "Publisher",
    action: "Publication failed",
    object: "robot-economy · release r4",
    detail: "Client payload rejected: anchor map missing s3",
    protected: true,
  },
  {
    id: "e4",
    time: "Yesterday · 16:04",
    actor: "Diego Alvarez",
    role: "Moderator",
    action: "Comment hidden",
    object: "reliability-paper · thread",
    detail: "Rule 2.1 harassment · appeal window open",
    protected: true,
  },
  {
    id: "e5",
    time: "Jul 26 · 09:00",
    actor: "Sara Kim",
    role: "Publisher",
    action: "Version published",
    object: "reliability-paper · v2",
    detail: "Material correction with visible notice",
    protected: true,
  },
  {
    id: "e6",
    time: "Jul 24 · 14:12",
    actor: "System",
    role: "Administrator",
    action: "Rights expiry warning",
    object: "scaling · rights record",
    detail: "Syndication terms expire January 2027",
    protected: false,
  },
];

export const alerts: QueueAlert[] = [
  {
    id: "al1",
    tone: "danger",
    title: "Publication failed — The Robot Economy v2",
    detail: "Client payload rejected: anchor map missing s3. Fix preflight, then retry.",
    destination: "publishing",
  },
  {
    id: "al2",
    tone: "danger",
    title: "Podcast blocked — Grid Storage Deals",
    detail: "No time-aligned transcript and playback rights unconfirmed.",
    destination: "project/grid-storage",
  },
  {
    id: "al3",
    tone: "warn",
    title: "Market resolution due — Attention pricing",
    detail: "Closed Jul 15. Resolution evidence due Aug 2 (2 days).",
    destination: "markets",
  },
  {
    id: "al4",
    tone: "warn",
    title: "High-severity comment report",
    detail: "Harassment signal 0.92 on Reliability Thresholds. SLA 4 hours.",
    destination: "community",
  },
  {
    id: "al5",
    tone: "info",
    title: "Rights expiring — Against Scaling at All Costs",
    detail: "Syndication terms expire January 2027. Renewal owner unassigned.",
    destination: "project/scaling",
  },
];

